### ISSUE TITLE
cant find email so I upload boardview for ASUS P5A-B in one of your github projects :) its almost same board, just AT form factor

### ISSUE THREAD

**Issue by raszpl** [scrapcomputing/MCEBlaster#1]
cant find email, uploading here  https://www.youtube.com/watch?v=MigVZLc_Mgw
[ASUS P5a-b_1.05.7z.zip](https://github.com/user-attachments/files/16401720/ASUS.P5a-b_1.05.7z.zip)

HIP is in upper right corner U15, SS controlled by Q11 'VCC2DET'. this signal also goes near the W83781G to either:
-74 series logic chips
-ASUS "Asic"

Asus AS something something 256 is afaik just a bunch of logic gates
EDIT: my own vogons post: https://www.vogons.org/viewtopic.php?p=1120994#p1120994

**Comment by scrapcomputing** [comment]
Thanks!

**Comment by ImprovedTube** [comment]
you good? @raszpl  will give all my retro computing parts for youtube extension fixes.
