### ISSUE TITLE
Thru Hole Boards

### ISSUE THREAD

**Issue by AusPuf** [scrapcomputing/MCEBlaster#9]
I just assembled one and have found that the D Sub 9 is mounted on the wrong side of PCB as per the image thus no input signal flipped it around and it seems to work but with some issues, got find out if is a hardware problem

**Comment by scrapcomputing** [comment]
I am not sure I follow. Did you place the connector on the wrong side, or is the PCB layout wrong?
What kind of issues are you having ?

**Comment by AusPuf** [comment]
Seems the PCB layout is wrong had the boards made by PCBWay. I soldered the
D Sub 9 the way you have it in the image, I got no input signal error, so I
desoldered it and put it on the other side so now the pins match. ie. gnd
to gnd and pin 5 to pin 5. so now both D Subs are on the same side.

**Comment by scrapcomputing** [comment]
I checked the layout and the positioning of the DB9 connector looks correct to me. When looking at the back of the board (where the buttons are) GND should be the rightmost pin at the top row and the connector should be soldered at the back (as shown here: https://github.com/scrapcomputing/MCEBlaster/blob/main/img/MCEBlasterTHT_PCB_back.jpg?raw=true). Then the GND pin on the PCB should have continuity with pin 1 of the connector. So the marking "DB9 Connector Bottom" is the side where you do the soldering.

**Comment by AusPuf** [comment]
When the D Sub is soldered as shown in your image, the gnd on the pcb is
then connected to pin 5 of D Sub. I've included images of the board and the
plug. The pic of the D Sub has pin 1 (gnd) on the right side

**Comment by scrapcomputing** [comment]
Ah I think I know what's wrong. You must be using a female DB9 connector. You should be using a male DB9 connector instead. On the male connector the GND pin on the PCB connects to pin 1.

By the way the images don't seem to have gone through.

**Comment by AusPuf** [comment]
Your way no input signal i had to solder it on to the opposite side as in
the attached pic to get input signal.

**Comment by scrapcomputing** [comment]
Are you sure you are using a male DB9 connector ? Because on the Female connector the rightmost-pin connects to pin 1 not pin 5.

The images are not getting through, probably because you are sending them over email ?

**Comment by AusPuf** [comment]
Ah me stupid I'm using a DB9 female no wonder i'm having issues So Sorry

Thankyou

**Comment by scrapcomputing** [comment]
No problem, let me know if you run into any more issues.
